---
title: "FLs generate mating pairs"
author: "Samuel"
date: "9/3/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# setwd("Documents/research/projects/Lsax_fertilisation_time/")
library(dplyr)
dt = read.csv("../data/FLs_size_mm_sex_after_male.csv")
# head(dt)
dt_sex = split(dt, dt$sex)
dt_sex$female$fgroup = c("G1", "G5", "G30")
dt_sex$female = filter(dt_sex$female, size_mm > 8.5)
for (f in 1:nrow(dt_sex$female)) {
  success=FALSE
  i=1
  f_log = log(dt_sex$female$size_mm[f])
  while (!success) {
    m_row = sample_n(dt_sex$male, size = 1)
    m_idx = which(dt_sex$male$snail_ID==m_row[,"snail_ID"])
    m_log = log(m_row[,"size_mm"])
    or = round(f_log - m_log, 1)
    # cat(or, "\n")
    success = (or >= 0.2 & or <= 0.4)
    i = i + 1
    if (or >= 0.2 & or <= 0.4) {
      cat("Female ID", dt_sex$female$snail_ID[f], "matched with male ID", m_row[,"snail_ID"], "in time group",
          dt_sex$female$fgroup[f], "\n")
      dt_sex$male = dt_sex$male[-m_idx,]
    }
  }
}
```

